version: '3.4'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    networks:
      - mariaES

  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    ports:
      - "8848:8848"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./data/nacos:/home/nacos/data
      - ./logs/nacos:/home/nacos/logs
    networks:
      - mariaES

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: front
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - nacos
    networks:
      - mariaES

  service-auth:
    build:
      context: .
      dockerfile: Dockerfile
      target: service-auth
    container_name: "MariaES-Auth"
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - nacos
    networks:
      - mariaES

  service-user:
    build:
      context: .
      dockerfile: Dockerfile
      target: service-user
    container_name: "MariaES-User"
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - nacos
    networks:
      - mariaES

  service-exam:
    build:
      context: .
      dockerfile: Dockerfile
      target: service-exam
    container_name: "MariaES-Exam"
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - nacos
    networks:
      - mariaES

  service-grade:
    build:
      context: .
      dockerfile: Dockerfile
      target: service-grade
    container_name: "MariaES-Grade"
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - nacos
    networks:
      - mariaES

  service-page:
    build:
      context: .
      dockerfile: Dockerfile
      target: service-page
    container_name: "MariaES-Page"
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - nacos
    networks:
      - mariaES

  service-question:
    build:
      context: .
      dockerfile: Dockerfile
      target: service-question
    container_name: "MariaES-Question"
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - nacos
    networks:
      - mariaES

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway
    container_name: "MariaES-Gateway"
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - redis
      - nacos
    networks:
      - mariaES

networks:
  mariaES:
    driver: bridge