version: '3.4'

services:
  redis:
    image: redis:6.2.10
    container_name: MariaES-Redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    networks:
      - nacos
      - mysql
      - redis
      - mariaES

  mysql:
    image: mysql:8.0.27
    container_name: MariaES-MySQL
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mariaes
      MYSQL_ROOT_PASSWORD: mariaES@strong
      MYSQL_USER: mariaES
      MYSQL_PASSWORD: mariaES@strong
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - nacos
      - mysql
      - redis
      - mariaES

  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: MariaES-nacos
    ports:
      - "8848:8848"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./data/nacos:/home/nacos/data
      - ./logs/nacos:/home/nacos/logs
    networks:
      - nacos
      - mysql
      - redis
      - mariaES

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: "MariaES-Frontend"
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - nacos
    networks:
      - nacos
      - mysql
      - redis
      - mariaES

  service-auth:
    build:
      context: .
      dockerfile: Dockerfile
      target: service-auth
    container_name: "MariaES-Auth"
    restart: on-failure
    expose:
      - "8080"
    depends_on:
      - redis
      - nacos
    networks:
      - nacos
      - mysql
      - redis
      - mariaES

  service-user:
    build:
      context: .
      dockerfile: Dockerfile
      target: service-user
    container_name: "MariaES-User"
    restart: on-failure
    expose:
      - "8080"
    depends_on:
      - redis
      - nacos
    networks:
      - nacos
      - mysql
      - redis
      - mariaES

  service-exam:
    build:
      context: .
      dockerfile: Dockerfile
      target: service-exam
    container_name: "MariaES-Exam"
    restart: on-failure
    expose:
      - "8080"
    depends_on:
      - redis
      - nacos
    networks:
      - nacos
      - mysql
      - redis
      - mariaES

  service-grade:
    build:
      context: .
      dockerfile: Dockerfile
      target: service-grade
    container_name: "MariaES-Grade"
    restart: on-failure
    expose:
      - "8080"
    depends_on:
      - redis
      - nacos
    networks:
      - nacos
      - mysql
      - redis
      - mariaES

  service-page:
    build:
      context: .
      dockerfile: Dockerfile
      target: service-page
    container_name: "MariaES-Page"
    restart: on-failure
    expose:
      - "8080"
    depends_on:
      - redis
      - nacos
    networks:
      - nacos
      - mysql
      - redis
      - mariaES

  service-question:
    build:
      context: .
      dockerfile: Dockerfile
      target: service-question
    container_name: "MariaES-Question"
    restart: on-failure
    expose:
      - "8080"
    depends_on:
      - redis
      - nacos
    networks:
      - nacos
      - mysql
      - redis
      - mariaES

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway
    container_name: "MariaES-Gateway"
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - redis
      - nacos
    networks:
      - nacos
      - mysql
      - redis
      - mariaES

networks:
  mariaES:
  nacos:
  redis:
  mysql: