server:
  port: 7010

spring:
  application:
        name: service-auth

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mariaes?createDatabaseIfNotExist=true
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 5
        minimum-idle: 5
        idle-timeout: 30000
        pool-name: SpringBootHikariCP
        max-lifetime: 60000
        connection-timeout: 30000

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

  redis:
    port: 6379
    host: localhost
    database: 1

#    cloud:
#        nacos:
#          discovery:
#            server-addr: localhost:8848
grpc:
  client:
    service-user:
      address: discovery://default/service-user

sa-token:
  token-name: mariaES