server:
  port: 7006

spring:
  application:
    name: gateway
#  config:
#    import: nacos://
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.207.8:8848
#      config:
#        server-addr: http://120.48.101.178:8848
#        file-extension: yaml

mariaes:
  front:
    url: http://localhost:7001
