server:
  port: 7006

spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.207.8:8848

  redis:
    port: 6379
    host: localhost
    database: 1

mariaes:
  front:
    url: http://localhost:7001
