server:
  port: 80

spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.207.8:8848

  redis:
    host: redis
    port: 6379
    database: 1

mariaes:
  front:
    url: http://front:7001
