server:
  port: 7001
spring:
  application:
    name: service-question
  cloud:
#    nacos服务注册
    nacos:
      discovery:
        username: mariaes
        password: mariaes
        server-addr:
#    sentinel配置
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
        clientIp:
      eager: true

#    数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mariaes
    username: mariaes
    password: mariaes
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: SpringBootHikariCP
      max-lifetime: 60000
      connection-timeout: 30000