server:
  port: 7001
spring:
  application:
    name: service-question
#  cloud:
##    nacos服务注册
#    nacos:
#      discovery:
#        username: mariaes
#        password: mariaes
#        server-addr:
##    sentinel配置
#    sentinel:
#      transport:
#        dashboard: localhost:8080
#        port: 8719
#        clientIp:
#      eager: true

#    数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mariaes?createDatabaseIfNotExist=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: SpringBootHikariCP
      max-lifetime: 60000
      connection-timeout: 30000

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
grpc:
  server:
    port: 6566
  client:
    GLOBAL:
      address: discovery://default/service-question

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  mvc: #不配置swagger启动类会报错空指针
    pathmatch:
      matching-strategy: ant_path_matcher
