server:
  port: 7002


spring:
  application:
    name: service-user

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql/mariaes?createDatabaseIfNotExist=true
    username: mariaes
    password: mariaes
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: SpringBootHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc: #不配置swagger启动类会报错空指针
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848

grpc:
  server:
    port: 9002
    security:
      enabled: false




